nba/urls.py
from django.urls import path

from . import views

app_name = 'nba'
urlpatterns = [
	path('', views.nba_teams, name='nba_teams'),
	path('team/<str:tri_code>/', views.team_info, name='team_info'),
	path('<str:tri_code>/player/<int:playerId>', views.player_info, name='player_info'),
]

nba_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('nba/', include('nba.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nba/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.core.files import File
import urllib
import os

# Create your models here.
class Team(models.Model):
	team_name = models.CharField(max_length=200)
	tri_code = models.CharField(max_length=200)
	color = models.CharField(max_length=20)
	conference = models.CharField(max_length=30)
	division = models.CharField(max_length=10)
	updated_at = models.DateTimeField(auto_now=True)
	url = models.CharField(max_length=500)
	logo = models.ImageField(upload_to="static/logos", null=True)
	wins = models.CharField(max_length=3, default="")
	losses = models.CharField(max_length=3, default="")

	def __str__(self):
		return self.team_name
		
	def was_updated_recently(self):
		return self.updated_at >= timezone.now() - datetime.timedelta(days=30)
		
	def cache(self):
		if self.url and not self.logo:
			result = urllib.request.urlretrieve(self.url)
			self.logo.save(
					os.path.basename(self.url),
					File(open(result[0]))
					)
			self.save()

class Player(models.Model):
	first_name = models.CharField(max_length=200)
	last_name = models.CharField(max_length=200)
	team = models.ForeignKey(Team, on_delete=models.CASCADE)
	
	jersey = models.CharField(max_length=3, default="")
	height = models.CharField(max_length=5, default="")
	weight = models.CharField(max_length=6, default="")
	dob = models.CharField(max_length=200, default="")
	position = models.CharField(max_length=3, default="")
	college = models.CharField(max_length=200, default="")
	draft = models.CharField(max_length=200, default="")
	
	url = models.CharField(max_length=400, default="")
	image = models.ImageField(upload_to="static/player_pics", null=True)

	points = models.CharField(max_length=10)
	rebounds = models.CharField(max_length=10)
	assists = models.CharField(max_length=10)
	
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.first_name + " " + self.last_name
		
	def was_updated_recently(self):
		return self.updated_at >= timezone.now() - datetime.timedelta(days=1)
		
	def cache(self):
		try:
			if self.url and not self.image:
				result = urllib.request.urlretrieve(self.url)
				self.image.save(
						os.path.basename(self.url),
						File(open(result[0], 'rb'))
						)
				self.save()
		except:
			pass
			
class Schedule(models.Model):
	gameId = models.CharField(default="", max_length=50, unique=True)
	team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="team")
	opponent = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="opponent")
	date = models.DateTimeField()
	isHomeTeam = models.BooleanField()
	score = models.IntegerField(null=True)
	opponentScore = models.IntegerField(null=True)
	
	def __str__(self):
		if self.isHomeTeam:
			return self.opponent.team_name + " @ " + self.team.team_name
		else:
			return self.team.team_name + " @ " + self.opponent.team_name
	

nba/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import Team, Player, Schedule
import requests, datetime, pytz
from django.utils import timezone

# Create your views here.
def get_all_nba_teams():
	r = requests.get("http://data.nba.net/data/10s/prod/v1/2017/teams.json")
	r = r.json()['league']['standard']
	for i in r:
		if i['isNBAFranchise']:
			# nba_teams.append({'teamId': i['teamId'], 'fullName': i['fullName'], 'tricode': i['tricode']})		
			if Team.objects.filter(id=i['teamId']).exists():
				if not Team.objects.get(id=i['teamId']).was_updated_recently():
					team = Team(id=i['teamId'], 
								team_name=i['fullName'], 
								tri_code=i['tricode'],
								conference=i['confName'],
								division=i['divName'],
								url="http://stats.nba.com/media/img/teams/logos/" + i['tricode'] + "_logo.svg",
								)
					team.cache()
					team.save()
				else:
					break;
			else:
				team = Team(id=i['teamId'], 
							team_name=i['fullName'], 
							tri_code=i['tricode'],
							conference=i['confName'],
							division=i['divName'],
							url="http://stats.nba.com/media/img/teams/logos/" + i['tricode'] + "_logo.svg",
							)
				team.cache()
				team.save()

def get_team_colors():
	r = requests.get("http://data.nba.net/data/1h/prod/2017/teams_config.json")
	r=r.json()['teams']['config']
	for i in r:
		if Team.objects.filter(id=i['teamId']).exists():
			team = Team.objects.get(id=i['teamId'])
			if team.color == "":
				team.color = i['primaryColor']
				team.save()

def get_current_standings():
	now = datetime.datetime.now()
	r = ""
	try:
		date = str(now.year) + '%02d'%now.month + '%02d'%now.day
		r = requests.get("http://data.nba.net/data/10s/prod/v1/" + date +"/standings_all.json")
		r = r.json()['league']['standard']['teams']
	except:
		date = str(now.year) + '%02d'%now.month + '%02d'%(now.day-1)
		r = requests.get("http://data.nba.net/data/10s/prod/v1/" + date +"/standings_all.json")
		r = r.json()['league']['standard']['teams']
	for i in r:
		team = Team.objects.get(id=i['teamId'])
		team.wins = i['win']
		team.losses = i['loss']
		team.save()

# start page
def nba_teams(request):		
	get_all_nba_teams()
	teams = Team.objects.order_by('team_name')
	get_team_colors()
	get_current_standings()
	template = loader.get_template('nba/nba_teams.html')
	context = {
		'teams': teams,
	}
	return HttpResponse(template.render(context, request))

def get_player_stats(player):
	r = requests.get("http://data.nba.net/data/10s/prod/v1/2017/players/" + str(player.id) + "_profile.json")
	r = r.json()['league']['standard']['stats']['latest']
	player.points = r['ppg'] if r['ppg'] != '-1' else 'N/A'
	player.rebounds = r['rpg'] if r['rpg'] != '-1' else 'N/A'
	player.assists = r['apg'] if r['apg'] != '-1' else 'N/A'
	
def get_players_on_team(teamId):
	r = requests.get("http://data.nba.net/data/10s/prod/v1/2017/players.json")
	r = r.json()['league']['standard']
	team = Team.objects.get(id=teamId)
	for i in r:
		if str(teamId) == i['teamId']:
			if Player.objects.filter(id=i['personId']).exists():
				if not Player.objects.get(id=i['personId']).was_updated_recently():
					player = Player(id=i['personId'], 
									team=team,
									first_name=i['firstName'],
									last_name=i['lastName'],
									jersey=i['jersey'],
									height=i['heightFeet']+ "\'" + i['heightInches'] + '\"',
									weight=i['weightPounds'],
									dob=i['dateOfBirthUTC'],
									position=i['pos'],
									college=i['collegeName'],
									draft=i['draft']['seasonYear'] + " Round: " +i['draft']['roundNum'] + " Pick: " + i['draft']['pickNum'],
									url="https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/"+ i['personId'] +".png"
									)
					get_player_stats(player)
					player.cache()
					player.save()
				else:
					break;
			else:
				player = Player(id=i['personId'], 
								team=Team.objects.get(id=teamId),
								first_name=i['firstName'],
								last_name=i['lastName'],
								jersey=i['jersey'],
								height=i['heightFeet']+ "\'" + i['heightInches'] + '\"',
								weight=i['weightPounds'] + "lbs",
								dob=i['dateOfBirthUTC'],
								position=i['pos'],
								college=i['collegeName'],
								draft=i['draft']['seasonYear'] + " Round: " +i['draft']['roundNum'] + " Pick: " + i['draft']['pickNum'],
								url="https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/"+ i['personId'] +".png",)
				get_player_stats(player) 
				player.cache()
				player.save()

	
				
def get_team_schedule(teamId):
	r = requests.get("http://data.nba.net/data/10s/prod/v1/2017/teams/" + str(teamId) + "/schedule.json")
	r = r.json()['league']['standard']
	for i in r:
		dateUTC = i['startTimeUTC']
		gameTime = datetime.datetime(int(dateUTC[:4]), int(dateUTC[5:7]), int(dateUTC[8:10]), int(dateUTC[11:13]), int(dateUTC[14:16]), int(dateUTC[17:19]), int(dateUTC[20:22]), pytz.UTC)
		if Schedule.objects.filter(gameId=Team.objects.get(id=teamId).tri_code + "" + i['gameId']).exists():
			s = Schedule.objects.get(gameId=Team.objects.get(id=teamId).tri_code + "" + i['gameId'])
			if s.score and s.opponentScore:
				continue
			if i['statusNum']==3 and not s.score and not s.opponentScore:
				s.score = int(i['hTeam']['score']) if s.isHomeTeam else int(i['vTeam']['score'])
				s.opponentScore = int(i['vTeam']['score']) if s.isHomeTeam else int(i['vTeam']['score'])
				s.save()
		else:
			if i['seasonStageId']==2:
				isHomeTeam = i['isHomeTeam']
				opponentTeamId = int(i['hTeam']['teamId']) if not isHomeTeam else int(i['vTeam']['teamId'])
				score = None
				opponentScore=None
				if i['statusNum']==3:
					score = int(i['hTeam']['score']) if isHomeTeam else int(i['vTeam']['score'])
					opponentScore = int(i['hTeam']['score']) if not isHomeTeam else int(i['vTeam']['score'])
					game = Schedule(gameId=Team.objects.get(id=teamId).tri_code + "" + i['gameId'],
									date=gameTime,
									team=Team.objects.get(id=teamId),
									opponent=Team.objects.get(id=opponentTeamId),
									isHomeTeam=isHomeTeam,
									score=score,
									opponentScore=opponentScore)
					game.save()
				else:
					game = Schedule(gameId=Team.objects.get(id=teamId).tri_code + "" + i['gameId'],
									date=gameTime,
									team=Team.objects.get(id=teamId),
									opponent=Team.objects.get(id=opponentTeamId),
									isHomeTeam=isHomeTeam)
					game.save()
		

# get team info using tricode as link
def team_info(request, tri_code):
	team = Team.objects.get(tri_code=tri_code)
	get_players_on_team(team.id)
	get_team_schedule(team.id)
	players = team.player_set.all().order_by('last_name')
	schedule = team.team.filter(date__lt=timezone.now()).order_by('-date')[:5][::-1]
	template = loader.get_template('nba/team_roster.html')
	context = {
		'team': team,
		'players': players,
		'schedule': schedule,
	}
	return HttpResponse(template.render(context, request))

def player_info(request, tri_code, playerId):
	player = Player.objects.get(id=playerId)
	template = loader.get_template('nba/player_info.html')
	context = {
		'player': player,
	}
	return HttpResponse(template.render(context, request))

nba/templates/nba/nba_teams.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'nba/nba_teams.css' %}" />

<ul>
{% for team in teams %}
<div class="team_info" onmouseover="this.style='background-color:{{ team.color }};';" onmouseout="this.style='background-color:#313842';">
	<div style="display:inline-block;">
	<img src="{{team.logo.url}}" style="width:50; height:50;">
	</div>
	<div style="display:inline-block">
	<a href="{% url 'nba:team_info' team.tri_code %}"
	style="text-decoration:none; color:white">
	<h2>
		{{ team.team_name }}
	</h2>
	</a>
	</div>
</div>
{% endfor %}
</ul>

nba/templates/nba/player_info.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'nba/player_info.css' %}" />
<div id="pic">
	<img id="player_pic" src="{{player.image.url}}" >
</div>
<div id="player_card">
	<div id="basic_info">
		<p id="name"> {{player.first_name}} {{player.last_name}}</p>
		<p id="misc_info"> <a href="{% url 'nba:team_info' player.team.tri_code %}">{{player.team.team_name}}</a>, #{{player.jersey}}, {{player.position}} </p>
		<p style="display: inline-block; padding-right: 20px;">	Height: {{player.height}} </p>
		<p style="display: inline-block;"> Weight: {{player.weight}} lbs </p>
	</div>
	<img id="logo" src="{{player.team.logo.url}}">
	<div id="season_stats">
		<div class="basic_stats">
			<p class="ss_header">Points</p>
			<p class="stats">{{player.points}}</p>
		</div>
		<div class="basic_stats">
			<p class="ss_header">Rebounds</p>
			<p class="stats">{{player.rebounds}}</p>
		</div>
		<div class="basic_stats">
			<p class="ss_header">Assists</p>
			<p class="stats">{{player.assists}}</p>
		</div>
	</div>
	<div id=other_info>
		<p> Born: {{player.dob|slice:"5:7"}}/{{player.dob|slice:"8:10"}}/{{player.dob|slice:":4"}}</p>
		<p> College: {{player.college}} </p>
		<p> Draft: {{player.draft}} </p>
	</div>
</div>

nba/templates/nba/team_roster.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'nba/team_roster.css' %}" />

<img src="{{team.logo.url}}">

<div>
	<h1>{{ team.team_name }}</h1>
	<p id="record" style="margin:0;"> Record: {{team.wins}}-{{team.losses}} </p>
</div>

<h2> Roster </h2>
<table style="border:4px solid {{team.color}};">
	<tr>
		<th></th>
		<th> Points </th>
		<th> Rebounds </th>
		<th> Assists </th>
	</tr>
{% for player in players %}
	<tr>
		<td><a href="{% url 'nba:player_info' tri_code=player.team.tri_code playerId=player.id %}">{{ player.first_name }} {{ player.last_name }}</a></td>
		<td>{{ player.points }}</td>
		<td>{{ player.rebounds }}</td>
		<td>{{ player.assists }}</td>
	</tr>
{% endfor %}
</table>

{% for game in schedule %}
	{% if not game.isHomeTeam %}
		<p>{{game.team}}: {{game.score}}</p>
		<p>{{game.opponent}}: {{game.opponentScore}}</p>
	{% else %}
		<p>{{game.opponent}}: {{game.opponentScore}}</p>
		<p>{{game.team}}: {{game.score}}</p>
	{% endif %}
{% endfor %}